export const SHOW_TABBAR = 'SHOW_TABBAR';
export const HIDE_TABBAR = 'HIDE_TABBAR';
export const SELECTED_VALUE = 'SELECTED_VALUE';
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';